import { Inter } from "next/font/google";
import "./globals.css";
import logo from "@/images/logo.png"
import Head from "next/head";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Acsender",
  description: "Generated by create next app",
  
};

{/* <link
  rel="icon"
  href={logo}
  type="image/<generated>"
  sizes="<generated>"
/> */}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
